from __future__ import annotations

from functools import lru_cache
from typing import Dict, Optional

from aiops.skills.commands import SkillCommandsManager
from aiops.workflows.complexity_analyzer import analyze_task_complexity


@lru_cache(maxsize=1)
def get_skill_commands_manager() -> SkillCommandsManager:
    return SkillCommandsManager()


def skill_integration_middleware(state: Dict) -> Dict:
    """Detect skill commands and inject skill content into query."""
    query = (state.get("query") or "").strip()
    if not query:
        return state
    command_manager = get_skill_commands_manager()
    invoked_command: Optional[str] = None
    for cmd in command_manager.list_commands():
        if query.startswith(cmd):
            invoked_command = cmd
            break
    if not invoked_command:
        return state
    skill_content = command_manager.get_command_content(invoked_command)
    if not skill_content:
        return {
            **state,
            "context": {**state.get("context", {}), "skill_error": f"技能加载失败: {invoked_command}"},
        }
    user_instruction = query.replace(invoked_command, "").strip()
    enhanced_query = f"{skill_content}\n\n用户指令: {user_instruction}"
    return {
        **state,
        "query": enhanced_query,
        "context": {
            **state.get("context", {}),
            "skill_invoked": True,
            "skill_command": invoked_command,
            "skill_content": skill_content,
            "original_query": query,
            "user_instruction": user_instruction,
        },
    }


from aiops.skills.manager import SkillManager

def _is_consultation_query(state: Dict) -> bool:
    intent = (state.get("context") or {}).get("user_intent")
    if intent == "consultation":
        return True
    results = state.get("results", [])
    if results:
        sources = [r.get("source") for r in results]
        if sources and all(s == "knowledge_base" for s in sources):
            return True
    return False

def _auto_create_skill(state: Dict, next_state: Dict, task_complexity: Dict) -> bool:
    """Automatically create a skill from a complex task. Returns True if skill was created."""
    try:
        query = state.get("query", "").strip()
        if not query:
            return False
            
        if _is_consultation_query(state):
            print(f"Skipping skill auto-creation for consultation query: {query}")
            return False
            
        clean_query = query.lower()
        for prefix in ["how do i", "how to", "what is", "check", "verify", "analyze", "介绍一下", "查询", "如何"]:
            if clean_query.startswith(prefix):
                clean_query = clean_query[len(prefix):].strip()
                break
        
        words = clean_query.split()
        skill_name = "-".join(words[:5]) if words else "auto-skill"
        skill_name = skill_name.replace("?", "").replace("!", "").strip("-")
        
        if not skill_name:
            skill_name = "auto-generated-skill"

        final_answer = next_state.get("final_answer", "")
        workflow_steps = task_complexity.get("workflow_steps", [])
        
        content = f"""# {skill_name}

## 概述
Autogenerated skill based on query: "{query}".
This skill encapsulates the knowledge and steps required to address queries related to this topic.

## 输入参数
- `query`: 用户查询字符串 (默认值: "{query}")
- `verbose`: 是否显示详细信息 (默认值: false)

## 执行步骤
"""
        if workflow_steps:
            for i, step in enumerate(workflow_steps):
                content += f"{i+1}. {step}\n"
        else:
            content += "1. Analyze the user query.\n2. Retrieve relevant information.\n3. Synthesize the answer.\n"
            
        content += f"""
## 输出格式
- 返回类型: String
- 内容: 包含结构化的回答文本。

## 详细说明
{final_answer}

## 注意事项
- This skill was automatically generated by the system.
- Please review and refine before production use.
- **安全提示**: 本技能仅用于信息查询，不涉及系统修改操作。操作前请确认环境。
- **错误处理**: 如果查询失败，请检查输入参数是否正确。若遇到异常，请参考系统日志。

## 代码示例
```python
# 示例：如何调用此技能
result = agent.invoke_skill("skill_name", query="your query")
print(result)
```
"""

        manager = SkillManager()
        manager.create_skill(
            name=skill_name,
            content=content,
            category="custom",
            metadata={
                "description": f"Auto-generated skill for: {query}",
                "author": "system-auto-learner",
                "risk_level": "medium",
                "tags": ["auto-generated", "learning"],
            }
        )
        print(f"Successfully auto-created skill: {skill_name}")
        return True
        
    except Exception as e:
        # Don't fail the workflow if auto-creation fails
        print(f"Failed to auto-create skill: {e}")
        return False


def skill_solidification_middleware(state: Dict, next_state: Dict) -> Dict:
    """Append solidification nudge for complex tasks and trigger auto-creation."""
    if "final_answer" not in next_state:
        return next_state
    task_complexity = analyze_task_complexity(state, next_state)
    should_nudge = (
        task_complexity.get("step_count", 0) >= 5
        or ("error" in (state.get("query") or "").lower() and "success" in next_state["final_answer"].lower())
    )
    
    if should_nudge:
        created = _auto_create_skill(state, next_state, task_complexity)
        
        if created:
            print(f"Skill auto-created for query: {state.get('query')}")
            
        return {
            **next_state,
            "context": {
                **next_state.get("context", {}),
                "should_solidify": True,
                "solidification_candidate": {
                    "workflow": task_complexity.get("workflow_steps", []),
                    "complexity_score": task_complexity.get("complexity_score", 0),
                },
            },
        }
        
    return next_state
